### ISSUE TITLE
Combine efforts with webupd8team for packaging atom

### ISSUE THREAD

**Issue by PanderMusubi** [alanfranz/atom-text-editor-repository#9] opened 2016-11-21 08:28 UTC
The webupd8team by Alin Andrei and others also rolls Atom deb packages. Perhaps you guys can combine efforts in this. Making it less and better work for all. See also https://launchpad.net/~webupd8team/+archive/ubuntu/atom and https://launchpad.net/~webupd8team/+contactuser

This might also speed up the adoption of this package in the official repositories of Ubuntu and Debian.

**Comment by alanfranz** [comment] 2016-11-21 08:47
Hello @PanderMusubi , AFAIK the WebUpd8 team performs a REBUILD, while I just do an UPLOAD OF THE ORIGINAL PACKAGES. 

How should we join forces, in your opinion? My effort is minimal, there's an automated upload on a CI system. And if I were to "combine efforts", I'd probably try combining such effort with upstream Atom developers (I've already opened tickets and offered them my support, but got no response).

I doubt that atom will ever pickup in official Debian/Ubuntu repos; it's too fast-paced for that kind of target.

If you've got more focused suggestions, feel free to add them, but a generic "combine efforts" doesn't help much.

**Comment by PanderMusubi** [comment] 2016-11-21 09:08
Thanks for you positive critique. Having two PPAs is confusing for users. Which to choose and why is not clear. Perhaps the advantages and disadvantages could be listed somewhere.

Although updates are fast-paced, still it could be offered as a standard package. Via updates and soon via snap this is possible.

The list of lines in sources.list for many users is growing and growing and each release one has to upgrade the urls whenever a PPA supports a new release of Ubuntu. So that is a reason for getting it into Ubuntu.

But, that only goes well when support is frequent, hence this issue. It would be a compliment to all you guys' efforts that it appears in Ubuntu repos.

**Comment by alanfranz** [comment] 2016-11-21 09:28
@PanderMusubi if you can reach the right people and make it possible to land it in Ubuntu, I'll help you with the upload script (which is just something that parses an rss feed and adds it to a yum and apt repo, btw). But I cannot waste a lot of time for that target; the atom repo was something I did primarily for my own consumption, and then released to the public since there was some interest.

What's the difference with webupd8? I don't know :-) I only add official debs and rpms to a repository. webupd8 guys rebuild the whole source - I had some bugs in the past with their build that were not reproducibile with the "standard" build, hence I created this mirror.

**Comment by PanderMusubi** [comment] 2016-11-21 14:53
Asking Atom users to vote for https://bugs.launchpad.net/ubuntu/+bug/1317809 will help. It has already the status Triaged :smile:

**Comment by hotice** [comment] 2016-11-22 12:33
My PPA (the WebUpd8 Atom PPA) doesn't provide a proper Atom packaging, because Atom can't be built in Launchpad PPAs due to some limitations (Launchpad PPAs don't allow downloading external resources).

**Comment by alanfranz** [comment] 2017-01-08 09:50
@PanderMusubi @hotice 
I have published the parsing script that I used to retrieve the latest atom stable release. Now, whatever I retrieve is pushed to bintray, it should be a fairly pipeline to setup.

Feel free to do whatever you like with the script, I think we should involve the atom team, btw.

**Comment by alanfranz** [comment] 2019-05-21 13:18
Closing the project, since upstream maintainers now provide a repository.

**Closed as completed by alanfranz** 2019-05-21 13:18 UTC
